export function getMeta() {
	return {
		name: 'root',
		component: '::div',
		className:'interface-card',
		children: [{
			name:'interfaceHeader',
			component:'::div',
			children:[{
				name:'headerItem0',
				component:'::div',
				children:['票据类型：',{
					name:'invoiceType',
					component:'Select',
					defaultValue:'{{$getInvoiceDefaultValue()}}',
					style:{ width: 120 },
					onChange:'{{$invoiceTypeChange}}',
					children:'{{$getInvoiceOptions()}}'
					// [{
					// 	name:'invoiceType0',
					// 	component:'Select.Option',
					// 	value:'0',
					// 	children:'增值税专用发票'
					// },{
					// 	name:'invoiceType1',
					// 	component:'Select.Option',
					// 	value:1,
					// 	children:'增值税普通发票'
					// },{
					// 	name:'invoiceType2',
					// 	component:'Select.Option',
					// 	value:0,
					// 	children:'农产品发票'
					// }]
				}]
			},{
				name:'headerItem1',
				component:'::div',
				children:['纳税人身份：',{
					name:'vatTaxpayer',
					component:'Checkbox.Group',
					options:['一般纳税人','小规模'],
					defaultValue:['一般纳税人'],
					onChange:'{{$vatTaxpayerChange}}'
				}]
			},{
				name:'headerItem2',
				component:'::div',
				children:['支持行业：',{
					name:'industryIdList',
					component:'Checkbox.Group',
					options:['工业','商贸','服务','信息技术'],
					defaultValue:['工业'],
					onChange:'{{$industryChange}}'
				}]
			}]
		},{
			name:'interfaceBody',
			component:'::div',
			children:[{
				name:'tabs',
				component:'Tabs',
				defaultActiveKey:'0',
				onChange:'{{$tabsChange}}',
				children: [{
					name:'amountAndtax',
					tab:"金额/税率",
					component:'Tabs.TabPane',
					key:"0",
					children:getAmountAndtaxChild()
				},{
					name:'deductible',
					tab:"认证/抵扣",
					component:'Tabs.TabPane',
					key:"1",
					children:getDeductibleChild()
				},{
					name:'departAndEmployee',
					tab:"部门/人员",
					component:'Tabs.TabPane',
					key:"2",
					children:getDepartAndEmployeeChild()
				},{
					name:'goodsAndAmount',
					tab:"商品/数量",
					component:'Tabs.TabPane',
					key:"3",
					children:getGoodsAndAmountChild()
				},{
					name:'bankAccount',
					tab:"银行账号",
					component:'Tabs.TabPane',
					key:"4",
					children:getBankAccountChild()
				},{
					name:'auxInfo',
					tab:"辅助信息",
					component:'Tabs.TabPane',
					key:"5",
					children:getAuxInfoChild()
				},{
					name:'ext',
					tab:"数值扩展",
					component:'Tabs.TabPane',
					key:"6",
					children:getExtChild()
				},{
					name:'stringExt',
					tab:"字符扩展",
					component:'Tabs.TabPane',
					key:"7",
					children:getStringExtChild()
				}]
			}]
		}]
	}
}

function getAmountAndtaxChild(){
	return {
		name:'amountAndtax',
		component:'::div',
		children:[{
			name:'amount',
			component:'::div',
			children:[{
				name:'amountTitle',
				component:'::span',
				className:'settingLabel',
				children:'金额:'
			},{
				name:'amountRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("noTaxAmount")}}',
				children:[{
					name:'amountRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'amountRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'amountRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'tax',
			component:'::div',
			children:[{
				name:'taxTitle',
				component:'::span',
				className:'settingLabel',
				children:'税额:'
			},{
				name:'taxRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("tax")}}',
				children:[{
					name:'taxRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'taxRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'taxRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'taxAndAmount',
			component:'::div',
			children:[{
				name:'taxAndAmountTitle',
				component:'::span',
				className:'settingLabel',
				children:'价税合计:'
			},{
				name:'taxAndAmountRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("amount")}}',
				children:[{
					name:'taxAndAmountRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'taxAndAmountRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'taxAndAmountRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'deductibleAmount',
			component:'::div',
			children:[{
				name:'deductibleTitle',
				component:'::span',
				className:'settingLabel',
				children:'可抵扣进项税额:'
			},{
				name:'deductibleAmountRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("deductibleInputTax")}}',
				children:[{
					name:'deductibleAmountRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'deductibleAmountRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'deductibleAmountRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'taxRate',
			component:'::div',
			children:[{
				name:'taxRateTitle',
				component:'::span',
				className:'settingLabel',
				children:'税率:'
			},{
				name:'taxRate',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("taxRate")}}',
				children:[{
					name:'taxRate0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'taxRate1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'taxRate2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'taxNormal',
			component:'::div',
			children:['一般纳税人:(多选)',{
				component:'Checkbox.Group',
				options:['0%','1.5%','3%减按2%'],
				defaultValue:['0%'],
			}]
			// onChange:'{{$normalTaxerChange}}'
		},{
			name:'taxSmall',
			component:'::div',
			children:['一般纳税人:(多选)',{
				component:'Checkbox.Group',
				options:['0%','1.5%','3%减按2%'],
				defaultValue:['0%'],
			}]
			// onChange:'{{$normalTaxerChange}}'
		}]
	}
}
function getDeductibleChild(){
	return {
		name:'deductibleAndCertification',
		component:'::div',
		children:[{
			name:'certification',
			component:'::div',
			children:[{
				name:'certificationTitle',
				component:'::span',
				className:'settingLabel',
				children:'认证:'
			},{
				name:'certificationRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("isQualification")}}',
				children:[{
					name:'certificationRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'certificationRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'certificationRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'certificationMonth',
			component:'::div',
			children:[{
				name:'certificationMonthTitle',
				component:'::span',
				className:'settingLabel',
				children:'认证月份:'
			},{
				name:'certificationMonthRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("certificationMonth")}}',
				children:[{
					name:'certificationMonthRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'certificationMonthRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'certificationMonthRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'deductible',
			component:'::div',
			children:[{
				name:'deductibleTitle',
				component:'::span',
				className:'settingLabel',
				children:'抵扣:'
			},{
				name:'deductibleRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("isDeduct")}}',
				children:[{
					name:'deductibleRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'deductibleRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'deductibleRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'invoiceDate',
			component:'::div',
			children:[{
				name:'invoiceDateTitle',
				component:'::span',
				className:'settingLabel',
				children:'开票日期:'
			},{
				name:'invoiceDateRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("billingDate")}}',
				children:[{
					name:'invoiceDateRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'invoiceDateRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'invoiceDateRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'imAndRefund',
			component:'::div',
			children:[{
				name:'imAndRefundTitle',
				component:'::span',
				className:'settingLabel',
				children:'即征即退核算:'
			},{
				name:'imAndRefundRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("drawbackPolicy")}}',
				children:[{
					name:'imAndRefundRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'imAndRefundRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'imAndRefundRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		}]
	}
}
function getDepartAndEmployeeChild(){
	return {
		name:'departAndEmployee',
		component:'::div',
		children:[{
			name:'department',
			component:'::div',
			children:[{
				name:'departmentTitle',
				component:'::span',
				className:'settingLabel',
				children:'部门:'
			},{
				name:'departmentRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("department")}}',
				children:[{
					name:'departmentRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'departmentRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'departmentRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'employee',
			component:'::div',
			children:[{
				name:'employeeTitle',
				component:'::span',
				className:'settingLabel',
				children:'人员:'
			},{
				name:'employeeMonthRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("employee")}}',
				children:[{
					name:'employeeMonthRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'employeeMonthRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'employeeMonthRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'customer',
			component:'::div',
			children:[{
				name:'customerTitle',
				component:'::span',
				className:'settingLabel',
				children:'客户:'
			},{
				name:'customerRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("customer")}}',
				children:[{
					name:'customerRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'customerRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'customerRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'investor',
			component:'::div',
			children:[{
				name:'investorTitle',
				component:'::span',
				className:'settingLabel',
				children:'投资人:'
			},{
				name:'investorRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("investor")}}',
				children:[{
					name:'investorRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'investorRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'investorRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'creditor',
			component:'::div',
			children:[{
				name:'creditorTitle',
				component:'::span',
				className:'settingLabel',
				children:'债权人:'
			},{
				name:'creditorRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("creditor")}}',
				children:[{
					name:'creditorRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'creditorRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'creditorRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'obligor',
			component:'::div',
			children:[{
				name:'obligorTitle',
				component:'::span',
				className:'settingLabel',
				children:'债务人:'
			},{
				name:'obligorRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("obligor")}}',
				children:[{
					name:'obligorRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'obligorRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'obligorRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		}]
	}
}
function getGoodsAndAmountChild(){
	return {
		name:'goodsAndAmount',
		component:'::div',
		children:[{
			name:'goods',
			component:'::div',
			children:[{
				name:'goodsTitle',
				component:'::span',
				className:'settingLabel',
				children:'商品或服务名称:'
			},{
				name:'goodsRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("goods")}}',
				children:[{
					name:'goodsRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'goodsRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'goodsRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'assetsType',
			component:'::div',
			children:[{
				name:'assetsTypeTitle',
				component:'::span',
				className:'settingLabel',
				children:'资产分类:'
			},{
				name:'assetsTypeMonthRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("assetsType")}}',
				children:[{
					name:'assetsTypeMonthRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'assetsTypeMonthRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'assetsTypeMonthRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'assets',
			component:'::div',
			children:[{
				name:'assetsTitle',
				component:'::span',
				className:'settingLabel',
				children:'资产:'
			},{
				name:'assetsRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("assets")}}',
				children:[{
					name:'assetsRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'assetsRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'assetsRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'quantity',
			component:'::div',
			children:[{
				name:'quantityTitle',
				component:'::span',
				className:'settingLabel',
				children:'数量:'
			},{
				name:'quantityRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("number")}}',
				children:[{
					name:'quantityRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'quantityRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'quantityRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'price',
			component:'::div',
			children:[{
				name:'priceTitle',
				component:'::span',
				className:'settingLabel',
				children:'单价:'
			},{
				name:'priceRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("price")}}',
				children:[{
					name:'priceRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'priceRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'priceRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		}]
	}
}
function getBankAccountChild(){
	return {
		name:'bankAccount',
		component:'::div',
		children:[{
			name:'bankAccountSet',
			component:'::div',
			children:[{
				name:'bankAccountTitle',
				component:'::span',
				className:'settingLabel',
				children:'账户(银行账号):'
			},{
				name:'bankAccountRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("bankAccount")}}',
				children:[{
					name:'bankAccountRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'bankAccountRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'bankAccountRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'bankAccountCheck',
			component:'::div',
			children:[{
				name:'bankAccount1',
				component:'::div',
				children:['账号：',{
					name:'normalTaxer',
					component:'Checkbox.Group',
					options:['现金','银行存款','支付宝','微信'],
					defaultValue:['现金'],
					// onChange:'{{$normalTaxerChange}}'
				}]
			},{
				name:'option',
				component:'::div',
				children:['结算方式：',{
					name:'normalTaxer',
					component:'Checkbox.Group',
					options:['冲减预收款','客户欠款','冲减预付款','欠供应商款','冲员工借款','员工垫付'],
					defaultValue:['冲减预收款'],
					// onChange:'{{$normalTaxerChange}}'
				}]
			}]
		},{
			name:'othBankAccountSet',
			component:'::div',
			children:[{
				name:'othBankAccountSetTitle',
				component:'::span',
				className:'settingLabel',
				children:'对方账户(用于转账):'
			},{
				name:'othBankAccountSetRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("incomeAccount")}}',
				children:[{
					name:'othBankAccountSetRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'othBankAccountSetRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'othBankAccountSetRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		}]
	}
}
function getAuxInfoChild(){
	return {
		name:'auxInfo',
		component:'::div',
		children:[{
			name:'invoiceCode',
			component:'::div',
			children:[{
				name:'invoiceCodeTitle',
				component:'::span',
				className:'settingLabel',
				children:'票据编码:'
			},{
				name:'invoiceCodeRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("invoiceNO")}}',
				children:[{
					name:'invoiceCodeRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'invoiceCodeRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'invoiceCodeRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'penaltyType',
			component:'::div',
			children:[{
				name:'penaltyTypeTitle',
				component:'::span',
				className:'settingLabel',
				children:'罚款性质:'
			},{
				name:'penaltyTypeMonthRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("penaltyType")}}',
				children:[{
					name:'penaltyTypeMonthRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'penaltyTypeMonthRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'penaltyTypeMonthRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'loanTerm',
			component:'::div',
			children:[{
				name:'loanTermTitle',
				component:'::span',
				className:'settingLabel',
				children:'借款期限:'
			},{
				name:'loanTermRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("loanTerm")}}',
				children:[{
					name:'loanTermRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'loanTermRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'loanTermRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'abstract',
			component:'::div',
			children:[{
				name:'abstractTitle',
				component:'::span',
				className:'settingLabel',
				children:'摘要:'
			},{
				name:'abstractRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("abstract")}}',
				children:[{
					name:'abstractRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'abstractRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'abstractRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		},{
			name:'project',
			component:'::div',
			children:[{
				name:'projectTitle',
				component:'::span',
				className:'settingLabel',
				children:'项目:'
			},{
				name:'projectRadio',
				component:'Radio.Group',
				onChange:'{{$detailRadioChange("project")}}',
				children:[{
					name:'projectRadio0',
					component:'Radio',
					children:'必填',
					value:2
				},{
					name:'projectRadio1',
					component:'Radio',
					children:'选填',
					value:1
				},{
					name:'projectRadio2',
					component:'Radio',
					children:'不显示',
					value:0
				}]
			}]
		}]
	}
}
let extChild = [],
	stringExt = []

for(let i=0 ; i< 10;i++){
	extChild.push({
		name:'ext'+i,
		component:'::div',
		children:[{
			name:'ext'+i+'Title',
			component:'::span',
			className:'settingLabel',
			children:'数值扩展'+i+':'
		},{
			name:'ext'+i+'Radio',
			component:'Radio.Group',
			onChange:'{{$detailRadioChange("ext"+i)}}',
			children:[{
				name:'ext'+0+'Radio0',
				component:'Radio',
				children:'必填',
				value:'0'
			},{
				name:'ext'+0+'Radio1',
				component:'Radio',
				children:'选填',
				value:1
			},{
				name:'ext'+0+'Radio2',
				component:'Radio',
				children:'不显示',
				value:0
			}]
		},{
			name:'showTitle'+i,
			component:'::div',
			className:'showTitle',
			children:[{
				name:'title'+i,
				component:'::span',
				children:'显示标题:'
			},{
				name:'edit'+i,
				onChange:'{{$extTittleChange("extTitle"+i)}}',
				component:'Input',
				width:100
			}]
		}]
	})
}
for(let i=0; i<5;i++){
	stringExt.push({
		name:'stringExt'+i,
		component:'::div',
		children:[{
			name:'stringExt'+i+'Title',
			component:'::span',
			className:'settingLabel',
			children:'字符扩展'+i+':'
		},{
			name:'stringExt'+i+'Radio',
			component:'Radio.Group',
			onChange:'{{$detailRadioChange("stringExt"+i)}}',
			children:[{
				name:	'stringExt'+0+'Radio0',
				component:'Radio',
				children:'必填',
				value:'0'
			},{
				name:'stringExt'+0+'Radio1',
				component:'Radio',
				children:'选填',
				value:1
			},{
				name:'stringExt'+0+'Radio2',
				component:'Radio',
				children:'不显示',
				value:0
			}]
		},{
			name:'stringShowTitle'+i,
			component:'::div',
			className:'showTitle',
			children:[{
				name:'stringTitle'+i,
				component:'::span',
				children:'显示标题:'
			},{
				name:'stringEdit'+i,
				onChange:'{{$extTittleChange("stringExtTitle"+i)}}',
				component:'Input',
				width:100
			}]
		}]
	})
}
function getExtChild(){
	return {
		name:'ext',
		component:'::div',
		children:extChild
	}
}
function getStringExtChild(){
	return {
		name:'stringExt',
		component:'::div',
		children:stringExt
	}
}

export function getInitState() {
	return {
		data: {
			content: 'hello world',
			form:{
				vatTaxpayerSmall:undefined,
				vatTaxpayerNormal:undefined
			}
		}
	}
}
